version: '2'
services:
  tstappjhipster-app:
    image: tstappjhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATA_MONGODB_URI=mongodb://tstappjhipster-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=tstAppJhipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://tstappjhipster-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://tstappjhipster-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 8080:8080
  tstappjhipster-mongodb:
    extends:
      file: mongodb.yml
      service: tstappjhipster-mongodb
  tstappjhipster-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: tstappjhipster-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
